updated with CIFS for sharedata

diff --git a/mymount b/mymount
--- a/mymount
+++ b/mymount
@@ -3,23 +3,26 @@
 # This script mounts or unmounts my local NFS ISO share
 # Create a hard or soft link to mount-isos called unmount-isos
 
-## Define some variables
+## BEGIN VARIABLES
+
 # Paths on NAS
 nasserver="nas.tehmonk.com"
-nasbase="/mnt/vit-nas1"
-nasbackups="$nasserver:$nasbase/backups"
-nasisos="$nasserver:$nasbase/LAN-Storage/ISO_Store"
-nasshares="$nasserver:$nasbase/LAN-Storage/ShareData"
+nasbackups="${nasserver}:/mnt/vit-nas1/backups"
+nasisos="${nasserver}:/mnt/vit-nas1/LAN-Storage/ISO_Store"
+nasShareName="ShareData"
 
 # Local paths
-localbackups="/home/daryl/lanshares/backups"
-localisos="/home/daryl/lanshares/iso_store"
-localshares="/home/daryl/lanshares/sharedata"
+localbackups="${HOME}/lanshares/backups"
+localisos="${HOME}/lanshares/iso_store"
+localShareName="${HOME}/lanshares/sharedata"
 
 # get command that launched this script
-mycommand="$(basename $0)"
+mycommand="$(basename "$0")"
 
-## Functions
+## END VARIABLES
+
+## BEGIN FUNCTIONS
+
 # help function
 help() {
   # Display Help
@@ -31,7 +34,7 @@ help() {
   echo "valid mount-names:"
   echo "  -b, --backups   NFS share from NAS for docs and working files"
   echo "  -i, --isos      NFS share from NAS for OS ISO images"
-  echo "  -s, --shares    NFS share from NAS for various LAN shared directories"
+  echo "  -s, --shares    CIFS share from NAS for various LAN shared directories"
   echo "  -a, --all       All three of the above shares"
   echo
   echo "  -h, --help      Prints this message."
@@ -39,15 +42,26 @@ help() {
   exit 1
 }
 
-## Script Prerequisites
+mount_smb() {
+  mount -t cifs -o "${naspath[$i]}" "${localpath[$i]}" -o credentials=~/.smbcreds,uid="${userId}",gid="${userGid}",vers=3
+}
+
+mount_nfs() {
+  mount -o tcp,vers=3 -t nfs "${naspath[$i]}" "${localpath[$i]}"
+}
+
+## END FUNCTIONS
+
+## BEGIN PREREQUISITES
+
 # Script must be run as root or with sudo
 user=$(id -u)
-#echo $user
 
-if [[ $user > 0 ]];
+if [[ $user -gt 0 ]];
 then
   echo "This command requires root. Use sudo or switch to root"
   echo
+  echo "======================================================"
   help
 fi
 
@@ -63,23 +77,35 @@ if ! which mount.nfs; then
   help
 fi
 
+# get calling user ID and group ID
+userId=$(logname)
+userGid=$(id -g "$(logname)")
+
+## END PREREQUISITES
+
+## BEGIN SCRIPT
+
 # which mount are we working on?
 case $1 in
   -b | --backups)
+    mountReq="backups"
     naspath="$nasbackups"
     localpath="$localbackups"
     ;;
   -i | --isos)
+    mountReq="ISO-Store"
     naspath="$nasisos"
     localpath="$localisos"
     ;;
   -s | --shares)
-    naspath="$nasshares"
-    localpath="$localshares"
+    mountReq="ShareData"
+    naspath="$nasShareName"
+    localpath="$localShareName"
     ;;
   -a | --all)
-    naspath=("$nasbackups" "$nasisos" "$nasshares")
-    localpath=("$localbackups" "$localisos" "$localshares")
+    mountReq="all"
+    naspath=("$nasbackups" "$nasisos" "$nasShareName")
+    localpath=("$localbackups" "$localisos" "$localShareName")
     ;;
   -h | --help)
     help
@@ -89,30 +115,50 @@ case $1 in
     ;;
 esac
 
-# if called with mymount, mount the share
-# if called with unmount, unmount the share
-# a link must be made to mymount called myunmount
-if [[ ${#naspath[@]} -eq ${#localpath[@]} ]]; then
-  for i in ${!naspath[@]}; do
-    if [[ $mycommand == "mymount" ]]; then
-      if [ ! -d ${localpath[$i]} ]; then
-        mkdir -p ${localpath[$i]} || { echo "${localpath[$i]} does not exist and I cannot make it"; exit 1; }
-      fi
-      if findmnt --mountpoint "${localpath[$i]}" &> /dev/null; then
-        echo "${localpath[$i]} is already mounted"
-      else
-        mount -o tcp,vers=3 -t nfs ${naspath[$i]} ${localpath[$i]} || { echo "Failed to mount $1 at ${localpath[$i]}"; exit 1; }
-      fi
-    elif [[ $mycommand == "myunmount" ]]; then
-      umount ${localpath[$i]} || { echo "Failed to unmount ${localpath[$i]}"; exit 1; }
-    else
-      echo "I don't know how we got here. "'$mycommand'" isn't looking good"
-      exit 1
-    fi
-  done
-else
-  echo "Something went wrong!"
-  echo "Time to troubleshoot the script."
-  echo '$naspath does not have the same number of items as $localpath'
+## if called with mymount, mount the share
+## if called with unmount, unmount the share
+## a link must be made to mymount called myunmount
+
+# make sure array lengths are equal
+if [[ ${#naspath[@]} -ne ${#localpath[@]} ]]; then
+  echo "You shouldn't see this message. Something is broken..."
   exit 1
 fi
+
+for i in "${!naspath[@]}"; do
+  if [[ $mycommand == "mymount" ]]; then
+    # Try to create the mount directory if it doesn't exist
+    if [ ! -d "${localpath[$i]}" ]; then
+      mkdir -p "${localpath[$i]}" || { echo "${localpath[$i]} does not exist and I cannot make it"; exit 1; }
+    fi
+
+    # Check if already mounted
+    if findmnt --mountpoint "${localpath[$i]}" &> /dev/null; then
+      echo "${localpath[$i]} is already mounted"
+    fi
+
+    # Mount NFS or CIFS depending on number of paths
+    if [[ "${#naspath[@]}" -eq 1 ]]; then
+      if [ "$1" = "-b" ] || [ "$1" = "-i" ]; then
+        mount_nfs || { echo "Failed to mount $mountReq at ${localpath[$i]}"; exit 1; }
+      elif [ "$1" = "-s" ]; then 
+        mount_smb || { echo "Failed to mount $mountReq at ${localpath[$i]}"; exit 1; }
+      fi
+    elif [[ "${#naspath[@]}" -eq 3 ]]; then
+      if [ "$i" = 1 ] || [ "$i" = 2 ]; then
+        mount_nfs || { echo "Failed to mount $mountReq at ${localpath[$i]}"; exit 1; }
+      elif [ "$i" = 3 ]; then
+        mount_smb || { echo "Failed to mount $mountReq at ${localpath[$i]}"; exit 1; }
+      fi
+    fi
+
+  # Unmount the share
+  elif [[ $mycommand == "myunmount" ]]; then
+    umount "${localpath[$i]}" || { echo "Failed to unmount ${localpath[$i]}"; exit 1; }
+  else
+    echo "I don't know how we got here. "'$mycommand'" isn't looking good"
+    exit 1
+  fi
+done
+
+## END SCRIPT
